///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Store {
/*
{
  "addr": "서울특별시 강북구 솔매로 38 (미아동)",
  "code": "11817488",
  "created_at": "2020/07/03 11:00:00",
  "lat": 37.6254369,
  "lng": 127.0164096,
  "name": "승약국",
  "remain_stat": "plenty",
  "stock_at": "2020/07/02 18:05:00",
  "type": "01"
} 
*/

  String? addr;
  String? code;
  String? createdAt;
  num? lat;
  num? lng;
  String? name;
  String? remainStat;
  String? stockAt;
  String? type;

  Store({
    this.addr,
    this.code,
    this.createdAt,
    this.lat,
    this.lng,
    this.name,
    this.remainStat,
    this.stockAt,
    this.type,
  });
  Store.fromJson(Map<String, dynamic> json) {
    addr = json["addr"]?.toString();
    code = json["code"]?.toString();
    createdAt = json["created_at"]?.toString();
    lat = json["lat"]?.toDouble();
    lng = json["lng"]?.toDouble();
    name = json["name"]?.toString();
    remainStat = json["remain_stat"]?.toString();
    stockAt = json["stock_at"]?.toString();
    type = json["type"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["addr"] = addr;
    data["code"] = code;
    data["created_at"] = createdAt;
    data["lat"] = lat;
    data["lng"] = lng;
    data["name"] = name;
    data["remain_stat"] = remainStat;
    data["stock_at"] = stockAt;
    data["type"] = type;
    return data;
  }
}

class SomeRootEntity {
/*
{
  "count": 222,
  "stores": [
    {
      "addr": "서울특별시 강북구 솔매로 38 (미아동)",
      "code": "11817488",
      "created_at": "2020/07/03 11:00:00",
      "lat": 37.6254369,
      "lng": 127.0164096,
      "name": "승약국",
      "remain_stat": "plenty",
      "stock_at": "2020/07/02 18:05:00",
      "type": "01"
    }
  ]
} 
*/

  int? count;
  List<Store?>? stores;

  SomeRootEntity({
    this.count,
    this.stores,
  });
  SomeRootEntity.fromJson(Map<String, dynamic> json) {
    count = json["count"]?.toInt();
    if (json["stores"] != null) {
      final v = json["stores"];
      final arr0 = <Store>[];
      v.forEach((v) {
        arr0.add(Store.fromJson(v));
      });
      stores = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["count"] = count;
    if (stores != null) {
      final v = stores;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["stores"] = arr0;
    }
    return data;
  }
}
